### ISSUE TITLE
[BUG] Mismatching module id

### ISSUE THREAD

**Issue by tytydraco** [Magisk-Modules-Alt-Repo/MacRandomizationEnabler#1]
On the [submission page](https://github.com/Magisk-Modules-Alt-Repo/submission#module-submissions), it states to make the repo name and the module id match. Otherwise, Magisk Manager will fail to show the README.md and also fail to install. Common mistake, I did the same thing 😄

**Comment by itz63c** [comment]
oh, TIL... fixing
