### ISSUE TITLE
It isn't showing up

### ISSUE THREAD

**Issue by bonbonboi** [Magisk-Modules-Alt-Repo/MacRandomizationEnabler#4]
Device: Redmi Note 4 (mido)
Android: 11

**Comment by chickendrop89** [comment]
it's because the WLAN driver used by mido does not support MAC Randomisation.

**Comment by chkndrp** [comment]
I think it's because the WLAN (prima) driver used by mido (SDM625) does **not** support MAC Randomization, and it isn't going to show up even with this module installed.
